/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JuEIC
 */
public class Cadastro extends javax.swing.JFrame {
    String cursos[]= new String[10]; 
    int cadastros = 0;
 
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        rbPresencial = new javax.swing.JRadioButton();
        rbSemi = new javax.swing.JRadioButton();
        rbEad = new javax.swing.JRadioButton();
        cbMatutino = new javax.swing.JCheckBox();
        cbIntegral = new javax.swing.JCheckBox();
        cbNoturno = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        tbMatricula = new javax.swing.JToggleButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Curso");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Modalidade");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Período");

        textNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textNome.setForeground(new java.awt.Color(51, 51, 51));
        textNome.setText("Nome do curso");

        buttonGroup1.add(rbPresencial);
        rbPresencial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPresencial.setText("Presencial");
        rbPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPresencialActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbSemi);
        rbSemi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSemi.setText("Semi-presencial");
        rbSemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSemiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbEad);
        rbEad.setSelected(true);
        rbEad.setText("EAD");
        rbEad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEadActionPerformed(evt);
            }
        });

        cbMatutino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbMatutino.setText("Matutino");

        cbIntegral.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbIntegral.setText("Integral");

        cbNoturno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbNoturno.setText("Noturno");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Matrículas");

        tbMatricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbMatricula.setText("Matrículas Abertas");
        tbMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMatriculaActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbPresencial)
                                            .addComponent(cbMatutino))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbIntegral)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbNoturno))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbSemi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rbEad))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tbMatricula)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnCancelar)
                                        .addGap(42, 42, 42)
                                        .addComponent(btnSalvar)))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbPresencial)
                    .addComponent(rbSemi)
                    .addComponent(rbEad))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMatutino)
                    .addComponent(cbIntegral)
                    .addComponent(cbNoturno))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tbMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPresencialActionPerformed
        // Alterar a ação do clique
        rbPresencial.setActionCommand("Presencial");
    }//GEN-LAST:event_rbPresencialActionPerformed

    private void tbMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMatriculaActionPerformed
        //Verificar a situação do botão
        if (tbMatricula.isSelected()){ // Alguém clicou?
            tbMatricula.setText("Matrículas Encerradas!");
        }else{
            tbMatricula.setText("Matrículas Abertas");
        }
    }//GEN-LAST:event_tbMatriculaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //Coletar digitação e seleção
        String nomeCurso = textNome.getText();
        
        textNome.setText("Nome do curso");//Após coletar valor, reinicia o texto
        String modalidade = buttonGroup1.getSelection().getActionCommand();
        // Após coletar reinicia Rádio Button
        buttonGroup1.clearSelection();
        
        String periodo = "";
        if (cbMatutino.isSelected()){
            periodo = "Matutino/ ";
            cbMatutino.setSelected(false);
        }
        if(cbIntegral.isSelected()){
            periodo = periodo + "Integral/ ";
            cbIntegral.setSelected(false);
        }
        if(cbNoturno.isSelected()){
            periodo = periodo + "Noturno";
            cbNoturno.setSelected(false);
        }
        String matricula = tbMatricula.getText();
        
        // vários cursos??
        cursos[cadastros] = "Código: " + (cadastros+1) + " - Curso: " +nomeCurso + "\n" +
                "Modalidade: "+ modalidade + " - Período: " + periodo + "\n" +
                "Matriculas: "+ matricula;

        cadastros++; //cadastro = cadastro + 1
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    
    private void rbSemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSemiActionPerformed
        rbSemi.setActionCommand("Semi-Presencial");
    }//GEN-LAST:event_rbSemiActionPerformed

    private void rbEadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEadActionPerformed
        rbEad.setActionCommand("EAD");
    }//GEN-LAST:event_rbEadActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbIntegral;
    private javax.swing.JCheckBox cbMatutino;
    private javax.swing.JCheckBox cbNoturno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbEad;
    private javax.swing.JRadioButton rbPresencial;
    private javax.swing.JRadioButton rbSemi;
    private javax.swing.JToggleButton tbMatricula;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
