
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JuEIC
 */
public class Cadastro extends javax.swing.JFrame {
    String cursos[] = new String[10];
    int cadastro = 0;

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jrbPresencial = new javax.swing.JRadioButton();
        jrbSemi = new javax.swing.JRadioButton();
        jrbEad = new javax.swing.JRadioButton();
        cbNoturno = new javax.swing.JCheckBox();
        cbIntegral = new javax.swing.JCheckBox();
        cbMatutino = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbMatricula = new javax.swing.JToggleButton();
        btnCancela = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Curso");

        textNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textNome.setText("Nome do curso");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Modalidade");

        buttonGroup1.add(jrbPresencial);
        jrbPresencial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbPresencial.setText("Presencial");
        jrbPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPresencialActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbSemi);
        jrbSemi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbSemi.setText("Semi- presencial");
        jrbSemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSemiActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbEad);
        jrbEad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbEad.setText("EAD");
        jrbEad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEadActionPerformed(evt);
            }
        });

        cbNoturno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbNoturno.setText("Noturno");

        cbIntegral.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbIntegral.setText("Integral");

        cbMatutino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbMatutino.setText("Matutino");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Período");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Situação");

        tbMatricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbMatricula.setText("Matriculas abertas");
        tbMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMatriculaActionPerformed(evt);
            }
        });

        btnCancela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancela.setText("Cancelar");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancela)
                        .addGap(43, 43, 43)
                        .addComponent(btnSalvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbMatricula)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMatutino)
                                    .addComponent(jrbPresencial))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbIntegral)
                                    .addComponent(jrbSemi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbNoturno)
                                    .addComponent(jrbEad))
                                .addGap(29, 29, 29)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbPresencial)
                    .addComponent(jrbEad)
                    .addComponent(jrbSemi)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMatutino)
                    .addComponent(jLabel2)
                    .addComponent(cbIntegral)
                    .addComponent(cbNoturno))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbMatricula)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancela))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMatriculaActionPerformed
        if (tbMatricula.isSelected()){
            tbMatricula.setText("Matriculas Encerradas");
        }else{
            tbMatricula.setText("Matriculas Abertas");
        }
    }//GEN-LAST:event_tbMatriculaActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //variáveis
        String nome, modalidade, periodo, matriculas = "";
        // Coletando seleções do usuário
        nome = textNome.getText();
        textNome.setText("");
        
        modalidade = buttonGroup1.getSelection().getActionCommand();
        buttonGroup1.clearSelection();
        
        periodo = "";
        if (cbMatutino.isSelected()){
            periodo = "Matutino/";
            cbMatutino.setSelected(false);
        }
        if(cbIntegral.isSelected()){
            periodo = periodo + " Integral/";
            cbIntegral.setSelected(false);
        }
        if (cbNoturno.isSelected()){
            periodo = periodo + " Noturno";
            cbNoturno.setSelected(false);
        }
        
        if(tbMatricula.isSelected()){
            matriculas = "Matrículas encerradas!";
        }else{
            matriculas = "Aceitando matrículas";
            tbMatricula.setSelected(false);
            
        }
        
        cursos[cadastro] = "Curso: "+ nome + "\n" + 
                "Modalidade: " + modalidade + "\n" + 
                "Período: " + periodo + "\n" +
                "Matriculas: " + matriculas;
        cadastro++;
        JOptionPane.showMessageDialog(this, "Cadastrado com secesso!");
        
        this.setVisible(false);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jrbPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPresencialActionPerformed
        jrbPresencial.setActionCommand("Presencial");
    }//GEN-LAST:event_jrbPresencialActionPerformed

    private void jrbSemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSemiActionPerformed
        jrbSemi.setActionCommand("Semi-Presencial");
    }//GEN-LAST:event_jrbSemiActionPerformed

    private void jrbEadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEadActionPerformed
        jrbEad.setActionCommand("EAD");
    }//GEN-LAST:event_jrbEadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbIntegral;
    private javax.swing.JCheckBox cbMatutino;
    private javax.swing.JCheckBox cbNoturno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jrbEad;
    private javax.swing.JRadioButton jrbPresencial;
    private javax.swing.JRadioButton jrbSemi;
    private javax.swing.JToggleButton tbMatricula;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
